//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.UserQuestion = new HashSet<UserQuestion>();
        }
    
        public int QuestionID { get; set; }
        public string QuestionText { get; set; }
        public Nullable<int> OptionID { get; set; }
        public string Difficult { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string SubText { get; set; }
        public string AnswerKey { get; set; }
    
        public virtual Option Option { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserQuestion> UserQuestion { get; set; }
    }
}
