//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectLesson
    {
        public int SubjectLessonID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> LessonID { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
